version: '3.9'

services:
  sm-mysql-server:
    image : mariadb
    environment:
      - MARIADB_ROOT_PASSWORD = masukaja
      - MARIADB_DATABASE = sm-db
    ports:
      - "3306:3306"
  stock-management:
    build: .
    container_name : sm-1.0
    ports:
      - "19000:8080"
    env_file:
      - config.env
